// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

// Default [FirebaseOptions] for use with your Firebase apps.

/*import 'firebase_options.dart';

await Firebase.initializeApp(
   options: DefaultFirebaseOptions.currentPlatform,
 );*/

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnzSZ9CNuv19dPca25TUl287VL-tXRFyY',
    appId: '1:277759358712:web:abbca871c40a1c4310ad0d',
    messagingSenderId: '277759358712',
    projectId: 'barber-shop-53434',
    authDomain: 'barber-shop-53434.firebaseapp.com',
    storageBucket: 'barber-shop-53434.appspot.com',
    measurementId: 'G-6YB1GCD0N7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGrxv9AtTIqGGl86inKjSVcMBxxZmHK4I',
    appId: '1:277759358712:android:5be878a99bdbd54d10ad0d',
    messagingSenderId: '277759358712',
    projectId: 'barber-shop-53434',
    storageBucket: 'barber-shop-53434.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOfN6exLBfKAskB59j7X8m9lWCeg3Av9k',
    appId: '1:277759358712:ios:c20dffac2c21a33d10ad0d',
    messagingSenderId: '277759358712',
    projectId: 'barber-shop-53434',
    storageBucket: 'barber-shop-53434.appspot.com',
    iosClientId:
        '277759358712-uog136lmjkohbi7cps6in6ufgrhg0c0i.apps.googleusercontent.com',
    iosBundleId: 'com.example.myfirstapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOfN6exLBfKAskB59j7X8m9lWCeg3Av9k',
    appId: '1:277759358712:ios:25dd1c219bb89e1810ad0d',
    messagingSenderId: '277759358712',
    projectId: 'barber-shop-53434',
    storageBucket: 'barber-shop-53434.appspot.com',
    iosClientId:
        '277759358712-3ljlnaso83tdk76e768h2o69gd744880.apps.googleusercontent.com',
    iosBundleId: 'com.example.myfirstapp.RunnerTests',
  );
}
